matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
      before_install: cd parser      
      install:
        - pip install pipenv
        - pipenv install
      script: pytest
