version: 2
jobs:
  build_app:
    docker:
      - image: circleci/openjdk:8-jdk
      
    steps:
      - checkout
      - run: ./gradlew clean build
          
  test_parser:
    docker:
      - image: circleci/python:3.7.3
      
    steps:
      - checkout
      - run: |
          cd parser
          pipenv install --dev
      - run: |
          cd parser
          pipenv run pytest
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build_app
      - test_parser
