version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      
    steps:
      - checkout

      - restore_cache:
          keys:
            - gradle-{{ checksum "frontend/build.gradle" }}-{{ checksum "backend/build.gradle" }}
            - gradle-
            
      - restore_cache:
          keys:
            - npm-{{ checksum "frontend/package-lock.json" }}
            - npm-

      - run: ./gradlew clean build
      
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "frontend/build.gradle" }}-{{ checksum "backend/build.gradle" }}
          
      - save_cache:
          paths:
            - frontend/node_modules
          key: npm-{{ checksum "frontend/package-lock.json" }}
          
  test_parser:
    docker:
      - image: circleci/python:3.7.3
      
    steps:
      - checkout
      - run: |
          cd parser
          pipenv install --dev
      - run: |
          cd parser
          pipenv run pytest
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_parser
